### ISSUE TITLE
dotnet coverage merge leads to filenames with the leading characters "/_/" in the filenames which bricks other tools

### ISSUE THREAD

**Issue by DerGary** [microsoft/codecoverage#101]
I have got 2 projects in one solution. The first project is the source code and the second project is the xunit test project.

Reproduction Steps:
- dotnet test -c Release --collect:"Code Coverage"
- dotnet coverage merge ./**/*.coverage -f cobertura -o mergedResult.cobertura.xml

The unit test files are getting the absolute path as filenames:
![image](https://github.com/microsoft/codecoverage/assets/4302467/23b7f21d-a0cf-410a-a358-9e228d12d870)

the source code files are getting a relative path with leading /_/
![image](https://github.com/microsoft/codecoverage/assets/4302467/692a526a-c73b-4227-a306-b3ba206db7ae)

Then Sonarqube for example can't find the files.

**Comment by jakubch1** [comment]
Thanks for reporting this. I've fixed issue in https://dev.azure.com/dnceng/public/_artifacts/feed/test-tools/NuGet/Microsoft.CodeCoverage/overview/17.10.0-preview-24120-01. I've added logic to resolve full paths by default. There is also configuration flag `DeterministicReport` to skip resolving and keep relative paths.

**Comment by DerGary** [comment]
@jakubch1 We still experience this issue with the latest version 17.11.3. Do you have an idea why?
