### ISSUE TITLE
Cobertura output does not contain code coverage for partial classes

### ISSUE THREAD

**Issue by Cjewett** [microsoft/codecoverage#19]
I'm moving our projects from Coverlet to Microsoft.CodeCoverage and I noticed that some of our partial classes are not being included in the Cobertura output. Is this a bug or is there something we're missing?

**Comment by jakubch1** [comment]
Could you please attach your report? When I run it locally I see separated `class` tags for each partial class.

**Comment by adc-cjewett** [comment]
@jakubch1 Provided the information below.

<details>
<summary>Cobertura Report</summary>

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<coverage line-rate="0.990990990990991" branch-rate="1" complexity="52" version="1.9" timestamp="1678847235" lines-covered="110" lines-valid="111" branches-covered="46" branches-valid="46">
  <packages>
    <package line-rate="0.990990990990991" branch-rate="0" complexity="52" name="CodeCoverageConverter">
      <classes>
        <class line-rate="0.9903846153846154" branch-rate="1" complexity="49" name="CodeCoverageConverter.CoverageFormats.BitbucketFormat.Bitbucket" filename="C:\FalcorApplications\codecoverageconverter\src\CodeCoverageConverter\CoverageFormats\BitbucketFormat\Bitbucket.cs">
          <methods>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="()">
              <lines>
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name="get_Files" signature="()">
              <lines>
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_Files" signature="(System.Collections.Generic.List&lt;CodeCoverageConverter.CoverageFormats.BitbucketFormat.File&gt;)">
              <lines>
                <line number="10" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="10" name=".ctor" signature="(CodeCoverageConverter.CoverageFormats.CoberturaFormat.Coverage, string, string)">
              <lines>
                <line number="10" hits="1" branch="False" />
                <line number="13" hits="1" branch="False" />
                <line number="14" hits="1" branch="False" />
                <line number="15" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="16" hits="1" branch="False" />
                <line number="17" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="18" hits="1" branch="False" />
                <line number="19" hits="1" branch="False" />
                <line number="21" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="22" hits="1" branch="False" />
                <line number="23" hits="1" branch="False" />
                <line number="24" hits="1" branch="False" />
                <line number="29" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="30" hits="1" branch="False" />
                <line number="31" hits="1" branch="False" />
                <line number="32" hits="1" branch="False" />
                <line number="33" hits="1" branch="False" />
                <line number="36" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="37" hits="1" branch="False" />
                <line number="38" hits="1" branch="False" />
                <line number="39" hits="1" branch="False" />
                <line number="40" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="10" name=".ctor" signature="(CodeCoverageConverter.CoverageFormats.CoverageXmlFormat.CoverageDSPriv)">
              <lines>
                <line number="10" hits="1" branch="False" />
                <line number="11" hits="1" branch="False" />
                <line number="12" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="13" hits="1" branch="False" />
                <line number="14" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="15" hits="1" branch="False" />
                <line number="16" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="17" hits="1" branch="False" />
                <line number="18" hits="1" branch="False" />
                <line number="20" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="21" hits="1" branch="False" />
                <line number="22" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="23" hits="1" branch="False" />
                <line number="24" hits="1" branch="False" />
                <line number="25" hits="1" branch="False" />
                <line number="26" hits="1" branch="False" />
                <line number="28" hits="1" branch="False" />
                <line number="29" hits="1" branch="False" />
                <line number="30" hits="1" branch="False" />
                <line number="31" hits="1" branch="False" />
                <line number="32" hits="1" branch="False" />
                <line number="33" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="10" name=".ctor" signature="(CodeCoverageConverter.CoverageFormats.LcovFormat.Lcov, string)">
              <lines>
                <line number="10" hits="1" branch="False" />
                <line number="11" hits="1" branch="False" />
                <line number="12" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="13" hits="1" branch="False" />
                <line number="14" hits="1" branch="False" />
                <line number="16" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="17" hits="1" branch="False" />
                <line number="18" hits="1" branch="False" />
                <line number="19" hits="1" branch="False" />
                <line number="21" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="22" hits="1" branch="False" />
                <line number="23" hits="1" branch="False" />
                <line number="24" hits="1" branch="False" />
                <line number="26" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="27" hits="1" branch="False" />
                <line number="28" hits="1" branch="False" />
                <line number="29" hits="1" branch="False" />
                <line number="32" hits="1" branch="False" />
                <line number="33" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="34" hits="1" branch="False" />
                <line number="35" hits="1" branch="False" />
                <line number="36" hits="1" branch="False" />
                <line number="37" hits="1" branch="False" />
                <line number="38" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="16" name=".ctor" signature="(CodeCoverageConverter.CoverageFormats.OpenCoverFormat.CoverageSession, string, string)">
              <lines>
                <line number="10" hits="1" branch="False" />
                <line number="11" hits="1" branch="False" />
                <line number="12" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="13" hits="1" branch="False" />
                <line number="14" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="15" hits="1" branch="False" />
                <line number="16" hits="1" branch="False" />
                <line number="19" hits="1" branch="False" />
                <line number="20" hits="1" branch="False" />
                <line number="22" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="23" hits="1" branch="False" />
                <line number="24" hits="1" branch="False" />
                <line number="25" hits="1" branch="False" />
                <line number="27" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="28" hits="1" branch="False" />
                <line number="29" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="30" hits="1" branch="False" />
                <line number="32" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="33" hits="1" branch="False" />
                <line number="34" hits="1" branch="False" />
                <line number="37" hits="1" branch="False" />
                <line number="38" hits="1" branch="False" />
                <line number="39" hits="1" branch="False" />
                <line number="41" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="42" hits="1" branch="False" />
                <line number="43" hits="1" branch="True" condition-coverage="100% (2/2)">
                  <conditions>
                    <condition number="0" type="jump" coverage="100%" />
                  </conditions>
                </line>
                <line number="44" hits="1" branch="False" />
                <line number="45" hits="1" branch="False" />
                <line number="46" hits="1" branch="False" />
                <line number="47" hits="1" branch="False" />
                <line number="48" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="7" hits="1" branch="False" />
            <line number="8" hits="1" branch="False" />
            <line number="10" hits="1" branch="False" />
            <line number="11" hits="1" branch="False" />
            <line number="12" hits="1" branch="True" condition-coverage="100% (2/2)">
              <conditions>
                <condition number="0" type="jump" coverage="100%" />
              </conditions>
            </line>
            <line number="13" hits="1" branch="False" />
            <line number="14" hits="1" branch="False" />
            <line number="15" hits="1" branch="True" condition-coverage="100% (2/2)">
              <conditions>
                <condition number="0" type="jump" coverage="100%" />
              </conditions>
            </line>
            <line number="16" hits="1" branch="False" />
            <line number="17" hits="1" branch="True" condition-coverage="100% (2/2)">
              <conditions>
                <condition number="0" type="jump" coverage="100%" />
              </conditions>
            </line>
            <line number="18" hits="1" branch="False" />
            <line number="19" hits="1" branch="False" />
            <line number="20" hits="1" branch="True" condition-coverage="100% (2/2)">
              <conditions>
                <condition number="0" type="jump" coverage="100%" />
              </conditions>
            </line>
            <line number="21" hits="1" branch="True" condition-coverage="100% (2/2)">
              <conditions>
                <condition number="0" type="jump" coverage="100%" />
              </conditions>
            </line>
            <line number="22" hits="1" branch="False" />
            <line number="23" hits="1" branch="False" />
            <line number="24" hits="1" branch="False" />
            <line number="25" hits="1" branch="False" />
            <line number="26" hits="1" branch="False" />
            <line number="27" hits="1" branch="False" />
            <line number="28" hits="1" branch="False" />
            <line number="29" hits="1" branch="True" condition-coverage="100% (2/2)">
              <conditions>
                <condition number="0" type="jump" coverage="100%" />
              </conditions>
            </line>
            <line number="30" hits="1" branch="False" />
            <line number="31" hits="1" branch="False" />
            <line number="32" hits="1" branch="False" />
            <line number="33" hits="1" branch="False" />
            <line number="34" hits="1" branch="False" />
            <line number="35" hits="1" branch="False" />
            <line number="36" hits="1" branch="True" condition-coverage="100% (2/2)">
              <conditions>
                <condition number="0" type="jump" coverage="100%" />
              </conditions>
            </line>
            <line number="37" hits="1" branch="False" />
            <line number="38" hits="1" branch="False" />
            <line number="39" hits="1" branch="False" />
            <line number="40" hits="1" branch="False" />
            <line number="41" hits="1" branch="True" condition-coverage="100% (2/2)">
              <conditions>
                <condition number="0" type="jump" coverage="100%" />
              </conditions>
            </line>
            <line number="42" hits="1" branch="False" />
            <line number="43" hits="1" branch="True" condition-coverage="100% (2/2)">
              <conditions>
                <condition number="0" type="jump" coverage="100%" />
              </conditions>
            </line>
            <line number="44" hits="1" branch="False" />
            <line number="45" hits="1" branch="False" />
            <line number="46" hits="1" branch="False" />
            <line number="47" hits="1" branch="False" />
            <line number="48" hits="1" branch="False" />
          </lines>
        </class>
        <class line-rate="1" branch-rate="1" complexity="3" name="CodeCoverageConverter.CoverageFormats.BitbucketFormat.File" filename="C:\FalcorApplications\codecoverageconverter\src\CodeCoverageConverter\CoverageFormats\BitbucketFormat\File.cs">
          <methods>
            <method line-rate="1" branch-rate="1" complexity="1" name="get_Path" signature="()">
              <lines>
                <line number="5" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name="get_Coverage" signature="()">
              <lines>
                <line number="6" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="(string, string)">
              <lines>
                <line number="8" hits="1" branch="False" />
                <line number="9" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
                <line number="11" hits="1" branch="False" />
                <line number="12" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="5" hits="1" branch="False" />
            <line number="6" hits="1" branch="False" />
            <line number="8" hits="1" branch="False" />
            <line number="9" hits="1" branch="False" />
            <line number="10" hits="1" branch="False" />
            <line number="11" hits="1" branch="False" />
            <line number="12" hits="1" branch="False" />
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
```
</details>

<details>
<summary>Partial Class Definitions</summary>

```csharp
namespace CodeCoverageConverter.CoverageFormats.BitbucketFormat
{
    public partial class Bitbucket
    {
        public Bitbucket()
        { }
    }
}
```

```csharp
namespace CodeCoverageConverter.CoverageFormats.BitbucketFormat
{
    public partial class Bitbucket
    {
        public Bitbucket(Coverage coverage, string directoryPath, string directoryPathToReplace)
        {
        }
    }
}
```

```csharp
namespace CodeCoverageConverter.CoverageFormats.BitbucketFormat
{
    public partial class Bitbucket
    {
        public Bitbucket(CoverageDSPriv coverageDSPriv)
        {
        }
    }
}
```

```csharp
namespace CodeCoverageConverter.CoverageFormats.BitbucketFormat
{
    public partial class Bitbucket
    {
        public Bitbucket(Lcov lcov, string directoryPath = "")
        {
        }
    }
}
```

```csharp
namespace CodeCoverageConverter.CoverageFormats.BitbucketFormat
{
    public partial class Bitbucket
    {
       public Bitbucket(CoverageSession coverageSession, string directoryPath, string directoryPathToReplace)
        {
        }
    }
}
```
</details>

<details>
<summary>Runsettings</summary>

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- Configurations that affect the Test Framework. -->
  <RunConfiguration>
    <!-- Path relative to solution directory. -->
    <ResultsDirectory>./TestResults</ResultsDirectory>
    <!-- Empty test projects are not allowed because they won't generate a trx file. -->
    <TreatNoTestsAsError>true</TreatNoTestsAsError>
  </RunConfiguration>
  <!-- Configuration for loggers. -->
  <LoggerRunSettings>
    <Loggers>
      <Logger uri="logger://Microsoft/TestPlatform/TrxLogger/v1">
        <Configuration>
          <!-- <LogFileName></LogFileName> -->
          <LogFileName>CodeCoverageConverterTests.trx</LogFileName>
        </Configuration>
      </Logger>
    </Loggers>
  </LoggerRunSettings>
  <!-- Configurations for data collectors. -->
  <DataCollectionRunSettings>
    <DataCollectors>
      <DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
        <Configuration>
          <Format>cobertura</Format>
          <!-- <CoverageFileName></CoverageFileName> -->
          <CodeCoverage>
            <ModulePaths>
              <Include>
                <!-- <ModulePath></ModulePath> -->
                <ModulePath>CodeCoverageConverter</ModulePath>
              </Include>
              <Exclude>
                <ModulePath>Moq</ModulePath>
              </Exclude>
            </ModulePaths>
            <Sources>
              <Include>
                <!-- <Source></Source> -->
                <Source>CodeCoverageConverter.CoverageFormats.BitbucketFormat.Bitbucket</Source>
                <Source>CodeCoverageConverter.CoverageFormats.BitbucketFormat.CoberturaToBitbucket</Source>
                <Source>CodeCoverageConverter.CoverageFormats.BitbucketFormat.CoverageXmlToBitbucket</Source>
                <Source>CodeCoverageConverter.CoverageFormats.BitbucketFormat.LcovToBitbucket</Source>
                <Source>CodeCoverageConverter.CoverageFormats.BitbucketFormat.OpenCoverToBitbucket</Source>
                <Source>CodeCoverageConverter.CoverageFormats.BitbucketFormat.File</Source>
              </Include>
            </Sources>
            <UseVerifiableInstrumentation>true</UseVerifiableInstrumentation>
            <AllowLowIntegrityProcesses>true</AllowLowIntegrityProcesses>
            <CollectFromChildProcesses>true</CollectFromChildProcesses>
            <CollectAspDotNet>false</CollectAspDotNet>
          </CodeCoverage>
          <CoverageFileName>CodeCoverageConverterTests</CoverageFileName>
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
  <MSTest>
    <MapInconclusiveToFailed>true</MapInconclusiveToFailed>
    <CaptureTraceOutput>false</CaptureTraceOutput>
    <DeploymentEnabled>false</DeploymentEnabled>
  </MSTest>
</RunSettings>
```
</details>

**Comment by fhnaseer** [comment]
[CoberturaPartial.zip](https://github.com/microsoft/codecoverage/files/10989852/CoberturaPartial.zip)
@Cjewett I tried to repro this, but I am seeing one class entry per file.
`dotnet test --collect:"Code Coverage;Format=Cobertura"`

Can you please try this solution and verify if you get the same report or not?

<details>
<summary>Report</summary>

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<coverage line-rate="1" branch-rate="1" complexity="4" version="1.9" timestamp="1678964683" lines-covered="15" lines-valid="15">
  <sources />
  <packages>
    <package line-rate="1" branch-rate="0" complexity="1" name="TestProject1">
      <classes>
        <class line-rate="1" branch-rate="1" complexity="1" name="TestProject1.UnitTest1" filename="D:\Issues\CoberturaPartial\TestProject1\UnitTest1.cs">
          <methods>
            <method line-rate="1" branch-rate="1" complexity="1" name="TestMethod1" signature="()">
              <lines>
                <line number="10" hits="1" branch="False" />
                <line number="11" hits="1" branch="False" />
                <line number="12" hits="1" branch="False" />
                <line number="13" hits="1" branch="False" />
                <line number="14" hits="1" branch="False" />
                <line number="15" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="10" hits="1" branch="False" />
            <line number="11" hits="1" branch="False" />
            <line number="12" hits="1" branch="False" />
            <line number="13" hits="1" branch="False" />
            <line number="14" hits="1" branch="False" />
            <line number="15" hits="1" branch="False" />
          </lines>
        </class>
      </classes>
    </package>
    <package line-rate="1" branch-rate="0" complexity="3" name="ClassLibrary1">
      <classes>
        <class line-rate="1" branch-rate="1" complexity="1" name="ClassLibrary1.Class1" filename="D:\Issues\CoberturaPartial\ClassLibrary1\Class1.Add.cs">
          <methods>
            <method line-rate="1" branch-rate="1" complexity="1" name="Add" signature="(int, int)">
              <lines>
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="6" hits="1" branch="False" />
            <line number="7" hits="1" branch="False" />
            <line number="8" hits="1" branch="False" />
          </lines>
        </class>
        <class line-rate="1" branch-rate="1" complexity="1" name="ClassLibrary1.Class1" filename="D:\Issues\CoberturaPartial\ClassLibrary1\Class1.Multiply.cs">
          <methods>
            <method line-rate="1" branch-rate="1" complexity="1" name="Multiply" signature="(int, int)">
              <lines>
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="6" hits="1" branch="False" />
            <line number="7" hits="1" branch="False" />
            <line number="8" hits="1" branch="False" />
          </lines>
        </class>
        <class line-rate="1" branch-rate="1" complexity="1" name="ClassLibrary1.Class1" filename="D:\Issues\CoberturaPartial\ClassLibrary1\Class1.Subtract.cs">
          <methods>
            <method line-rate="1" branch-rate="1" complexity="1" name="Subtract" signature="(int, int)">
              <lines>
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="6" hits="1" branch="False" />
            <line number="7" hits="1" branch="False" />
            <line number="8" hits="1" branch="False" />
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>```
</details>

**Comment by adc-cjewett** [comment]
@fhnaseer I was able to use that project, execute the `dotnet test --collect:"Code Coverage;Format=Cobertura"` command, and get the same result as yours. FWIW the code we're testing is in a Microsoft.NET.Sdk.Web project.

Some things I tested quickly which were unsuccessful in fixing the issue:
Renaming our files to match your file format. Bitbucket.ToCobertura.cs, etc. 
Downgrade MSTest.TestAdapter and MSTest.TestFramework to 2.2.8
Downgrade Microsoft.NET.Test.Sdk to 17.1.0

I'll try to get a repro going and will ping here with an update.

**Comment by adc-cjewett** [comment]
@fhnaseer I believe I've reproduced the issue https://github.com/adc-cjewett/PartialClassCodeCoverage. I was able to replicate this behavior on two different machines. 

There is one Bitbucket.cs file that contains the code coverage for the Bitbucket partial class that has functionality in 4 different files.
There are two WeatherForecastController.cs outputs when I would only expect one.

**Comment by adc-cjewett** [comment]
@fhnaseer Understood on the WeatherForecastController. I think that's okay since the line numbers are different and in case of a merge of results it's not overwriting anything. 

For the partial classes I added the same function and see the same result.

<details>
<summary>Before</summary>

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<coverage line-rate="0.37142857142857144" branch-rate="0" complexity="26" version="1.9" timestamp="1679334743" lines-covered="26" lines-valid="70" branches-valid="4">
  <sources />
  <packages>
    <package line-rate="1" branch-rate="0" complexity="1" name="WebApplication.Tests">
      <classes>
        <class line-rate="1" branch-rate="1" complexity="1" name="WebApplication.Tests.UnitTest1" filename="C:\Github\PartialClassCodeCoverage\test\WebApplication.Tests\UnitTest1.cs">
          <methods>
            <method line-rate="1" branch-rate="1" complexity="1" name="TestMethod1" signature="()">
              <lines>
                <line number="10" hits="1" branch="False" />
                <line number="11" hits="1" branch="False" />
                <line number="12" hits="1" branch="False" />
                <line number="13" hits="1" branch="False" />
                <line number="14" hits="1" branch="False" />
                <line number="15" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="10" hits="1" branch="False" />
            <line number="11" hits="1" branch="False" />
            <line number="12" hits="1" branch="False" />
            <line number="13" hits="1" branch="False" />
            <line number="14" hits="1" branch="False" />
            <line number="15" hits="1" branch="False" />
          </lines>
        </class>
      </classes>
    </package>
    <package line-rate="0.3125" branch-rate="0" complexity="25" name="CodeCoverageRepro">
      <classes>
        <class line-rate="0" branch-rate="1" complexity="1" name=".Program" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\Program.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name="&lt;Main&gt;$" signature="(string[])">
              <lines>
                <line number="1" hits="0" branch="False" />
                <line number="5" hits="0" branch="False" />
                <line number="7" hits="0" branch="False" />
                <line number="11" hits="0" branch="False" />
                <line number="13" hits="0" branch="False" />
                <line number="15" hits="0" branch="False" />
                <line number="17" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="1" hits="0" branch="False" />
            <line number="5" hits="0" branch="False" />
            <line number="7" hits="0" branch="False" />
            <line number="11" hits="0" branch="False" />
            <line number="13" hits="0" branch="False" />
            <line number="15" hits="0" branch="False" />
            <line number="17" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0" branch-rate="1" complexity="7" name="CodeCoverageRepro.WeatherForecast" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\WeatherForecast.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Date" signature="()">
              <lines>
                <line number="5" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_Date" signature="(System.DateOnly)">
              <lines>
                <line number="5" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_TemperatureC" signature="()">
              <lines>
                <line number="7" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_TemperatureC" signature="(int)">
              <lines>
                <line number="7" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_TemperatureF" signature="()">
              <lines>
                <line number="9" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Summary" signature="()">
              <lines>
                <line number="11" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_Summary" signature="(string)">
              <lines>
                <line number="11" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="5" hits="0" branch="False" />
            <line number="7" hits="0" branch="False" />
            <line number="9" hits="0" branch="False" />
            <line number="11" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0" branch-rate="1" complexity="3" name="CodeCoverageRepro.CoverageFormats.Bitbucket.File" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\CoverageFormats\Bitbucket\File.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Path" signature="()">
              <lines>
                <line number="5" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Coverage" signature="()">
              <lines>
                <line number="6" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name=".ctor" signature="(string, string)">
              <lines>
                <line number="8" hits="0" branch="False" />
                <line number="9" hits="0" branch="False" />
                <line number="10" hits="0" branch="False" />
                <line number="11" hits="0" branch="False" />
                <line number="12" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="5" hits="0" branch="False" />
            <line number="6" hits="0" branch="False" />
            <line number="8" hits="0" branch="False" />
            <line number="9" hits="0" branch="False" />
            <line number="10" hits="0" branch="False" />
            <line number="11" hits="0" branch="False" />
            <line number="12" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0.8" branch-rate="1" complexity="7" name="CodeCoverageRepro.CoverageFormats.BitbucketFormat.Bitbucket" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\CoverageFormats\Bitbucket\Bitbucket.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name=".ctor" signature="()">
              <lines>
                <line number="7" hits="0" branch="False" />
                <line number="8" hits="0" branch="False" />
                <line number="10" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Files" signature="()">
              <lines>
                <line number="10" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_Files" signature="(System.Collections.Generic.List&lt;CodeCoverageRepro.CoverageFormats.Bitbucket.File&gt;)">
              <lines>
                <line number="10" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="(int)">
              <lines>
                <line number="5" hits="1" branch="False" />
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="(int, int)">
              <lines>
                <line number="5" hits="1" branch="False" />
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="(int, int, int)">
              <lines>
                <line number="5" hits="1" branch="False" />
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="(int, int, int, int)">
              <lines>
                <line number="5" hits="1" branch="False" />
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="5" hits="1" branch="False" />
            <line number="6" hits="1" branch="False" />
            <line number="7" hits="0" branch="False" />
            <line number="8" hits="0" branch="False" />
            <line number="10" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0" branch-rate="0" complexity="6" name="CodeCoverageRepro.Controllers.WeatherForecastController" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\Controllers\WeatherForecastController.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name=".ctor" signature="(Microsoft.Extensions.Logging.ILogger&lt;CodeCoverageRepro.Controllers.WeatherForecastController&gt;)">
              <lines>
                <line number="16" hits="0" branch="False" />
                <line number="17" hits="0" branch="False" />
                <line number="18" hits="0" branch="False" />
                <line number="19" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="0" complexity="4" name="Get" signature="()">
              <lines>
                <line number="23" hits="0" branch="False" />
                <line number="24" hits="0" branch="True" condition-coverage="0% (0/4)">
                  <conditions>
                    <condition number="0" type="jump" coverage="0%" />
                    <condition number="1" type="jump" coverage="0%" />
                  </conditions>
                </line>
                <line number="30" hits="0" branch="False" />
                <line number="31" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name=".cctor" signature="()">
              <lines>
                <line number="9" hits="0" branch="False" />
                <line number="10" hits="0" branch="False" />
                <line number="11" hits="0" branch="False" />
                <line number="12" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="9" hits="0" branch="False" />
            <line number="10" hits="0" branch="False" />
            <line number="11" hits="0" branch="False" />
            <line number="12" hits="0" branch="False" />
            <line number="16" hits="0" branch="False" />
            <line number="17" hits="0" branch="False" />
            <line number="18" hits="0" branch="False" />
            <line number="19" hits="0" branch="False" />
            <line number="23" hits="0" branch="False" />
            <line number="24" hits="0" branch="True" condition-coverage="0% (0/4)">
              <conditions>
                <condition number="0" type="jump" coverage="0%" />
                <condition number="1" type="jump" coverage="0%" />
              </conditions>
            </line>
            <line number="30" hits="0" branch="False" />
            <line number="31" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0" branch-rate="1" complexity="1" name="CodeCoverageRepro.Controllers.WeatherForecastController.&lt;&gt;c" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\Controllers\WeatherForecastController.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name="&lt;Get&gt;b__3_0" signature="(int)">
              <lines>
                <line number="24" hits="0" branch="False" />
                <line number="25" hits="0" branch="False" />
                <line number="26" hits="0" branch="False" />
                <line number="27" hits="0" branch="False" />
                <line number="28" hits="0" branch="False" />
                <line number="29" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="24" hits="0" branch="False" />
            <line number="25" hits="0" branch="False" />
            <line number="26" hits="0" branch="False" />
            <line number="27" hits="0" branch="False" />
            <line number="28" hits="0" branch="False" />
            <line number="29" hits="0" branch="False" />
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
```
</details>


<details>
<summary>After</summary>

```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<coverage line-rate="0.352112676056338" branch-rate="0" complexity="28" version="1.9" timestamp="1679409899" lines-covered="25" lines-valid="71" branches-valid="4">
  <sources />
  <packages>
    <package line-rate="1" branch-rate="0" complexity="1" name="WebApplication.Tests">
      <classes>
        <class line-rate="1" branch-rate="1" complexity="1" name="WebApplication.Tests.UnitTest1" filename="C:\Github\PartialClassCodeCoverage\test\WebApplication.Tests\UnitTest1.cs">
          <methods>
            <method line-rate="1" branch-rate="1" complexity="1" name="TestMethod1" signature="()">
              <lines>
                <line number="10" hits="1" branch="False" />
                <line number="11" hits="1" branch="False" />
                <line number="12" hits="1" branch="False" />
                <line number="13" hits="1" branch="False" />
                <line number="14" hits="1" branch="False" />
                <line number="15" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="10" hits="1" branch="False" />
            <line number="11" hits="1" branch="False" />
            <line number="12" hits="1" branch="False" />
            <line number="13" hits="1" branch="False" />
            <line number="14" hits="1" branch="False" />
            <line number="15" hits="1" branch="False" />
          </lines>
        </class>
      </classes>
    </package>
    <package line-rate="0.2923076923076923" branch-rate="0" complexity="27" name="CodeCoverageRepro">
      <classes>
        <class line-rate="0" branch-rate="1" complexity="1" name=".Program" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\Program.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name="&lt;Main&gt;$" signature="(string[])">
              <lines>
                <line number="1" hits="0" branch="False" />
                <line number="5" hits="0" branch="False" />
                <line number="7" hits="0" branch="False" />
                <line number="11" hits="0" branch="False" />
                <line number="13" hits="0" branch="False" />
                <line number="15" hits="0" branch="False" />
                <line number="17" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="1" hits="0" branch="False" />
            <line number="5" hits="0" branch="False" />
            <line number="7" hits="0" branch="False" />
            <line number="11" hits="0" branch="False" />
            <line number="13" hits="0" branch="False" />
            <line number="15" hits="0" branch="False" />
            <line number="17" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0" branch-rate="1" complexity="7" name="CodeCoverageRepro.WeatherForecast" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\WeatherForecast.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Date" signature="()">
              <lines>
                <line number="5" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_Date" signature="(System.DateOnly)">
              <lines>
                <line number="5" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_TemperatureC" signature="()">
              <lines>
                <line number="7" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_TemperatureC" signature="(int)">
              <lines>
                <line number="7" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_TemperatureF" signature="()">
              <lines>
                <line number="9" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Summary" signature="()">
              <lines>
                <line number="11" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_Summary" signature="(string)">
              <lines>
                <line number="11" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="5" hits="0" branch="False" />
            <line number="7" hits="0" branch="False" />
            <line number="9" hits="0" branch="False" />
            <line number="11" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0" branch-rate="1" complexity="3" name="CodeCoverageRepro.CoverageFormats.Bitbucket.File" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\CoverageFormats\Bitbucket\File.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Path" signature="()">
              <lines>
                <line number="5" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Coverage" signature="()">
              <lines>
                <line number="6" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name=".ctor" signature="(string, string)">
              <lines>
                <line number="8" hits="0" branch="False" />
                <line number="9" hits="0" branch="False" />
                <line number="10" hits="0" branch="False" />
                <line number="11" hits="0" branch="False" />
                <line number="12" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="5" hits="0" branch="False" />
            <line number="6" hits="0" branch="False" />
            <line number="8" hits="0" branch="False" />
            <line number="9" hits="0" branch="False" />
            <line number="10" hits="0" branch="False" />
            <line number="11" hits="0" branch="False" />
            <line number="12" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0.7916666666666666" branch-rate="1" complexity="7" name="CodeCoverageRepro.CoverageFormats.BitbucketFormat.Bitbucket" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\CoverageFormats\Bitbucket\Bitbucket.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name=".ctor" signature="()">
              <lines>
                <line number="7" hits="0" branch="False" />
                <line number="8" hits="0" branch="False" />
                <line number="10" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_Files" signature="()">
              <lines>
                <line number="10" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_Files" signature="(System.Collections.Generic.List&lt;CodeCoverageRepro.CoverageFormats.Bitbucket.File&gt;)">
              <lines>
                <line number="10" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="(int)">
              <lines>
                <line number="5" hits="1" branch="False" />
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="(int, int)">
              <lines>
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
                <line number="9" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="(int, int, int)">
              <lines>
                <line number="5" hits="1" branch="False" />
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
            <method line-rate="1" branch-rate="1" complexity="1" name=".ctor" signature="(int, int, int, int)">
              <lines>
                <line number="5" hits="1" branch="False" />
                <line number="6" hits="1" branch="False" />
                <line number="7" hits="1" branch="False" />
                <line number="8" hits="1" branch="False" />
                <line number="10" hits="1" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="5" hits="1" branch="False" />
            <line number="6" hits="1" branch="False" />
            <line number="7" hits="0" branch="False" />
            <line number="8" hits="0" branch="False" />
            <line number="9" hits="1" branch="False" />
            <line number="10" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0" branch-rate="1" complexity="2" name="CodeCoverageRepro.CoverageFormats.BitbucketFormat.Bitbucket" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\CoverageFormats\Bitbucket\CoverageXmlToBitbucket.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name="get_MoreFiles" signature="()">
              <lines>
                <line number="12" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name="set_MoreFiles" signature="(System.Collections.Generic.List&lt;CodeCoverageRepro.CoverageFormats.Bitbucket.File&gt;)">
              <lines>
                <line number="12" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="12" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0" branch-rate="0" complexity="6" name="CodeCoverageRepro.Controllers.WeatherForecastController" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\Controllers\WeatherForecastController.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name=".ctor" signature="(Microsoft.Extensions.Logging.ILogger&lt;CodeCoverageRepro.Controllers.WeatherForecastController&gt;)">
              <lines>
                <line number="16" hits="0" branch="False" />
                <line number="17" hits="0" branch="False" />
                <line number="18" hits="0" branch="False" />
                <line number="19" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="0" complexity="4" name="Get" signature="()">
              <lines>
                <line number="23" hits="0" branch="False" />
                <line number="24" hits="0" branch="True" condition-coverage="0% (0/4)">
                  <conditions>
                    <condition number="0" type="jump" coverage="0%" />
                    <condition number="1" type="jump" coverage="0%" />
                  </conditions>
                </line>
                <line number="30" hits="0" branch="False" />
                <line number="31" hits="0" branch="False" />
              </lines>
            </method>
            <method line-rate="0" branch-rate="1" complexity="1" name=".cctor" signature="()">
              <lines>
                <line number="9" hits="0" branch="False" />
                <line number="10" hits="0" branch="False" />
                <line number="11" hits="0" branch="False" />
                <line number="12" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="9" hits="0" branch="False" />
            <line number="10" hits="0" branch="False" />
            <line number="11" hits="0" branch="False" />
            <line number="12" hits="0" branch="False" />
            <line number="16" hits="0" branch="False" />
            <line number="17" hits="0" branch="False" />
            <line number="18" hits="0" branch="False" />
            <line number="19" hits="0" branch="False" />
            <line number="23" hits="0" branch="False" />
            <line number="24" hits="0" branch="True" condition-coverage="0% (0/4)">
              <conditions>
                <condition number="0" type="jump" coverage="0%" />
                <condition number="1" type="jump" coverage="0%" />
              </conditions>
            </line>
            <line number="30" hits="0" branch="False" />
            <line number="31" hits="0" branch="False" />
          </lines>
        </class>
        <class line-rate="0" branch-rate="1" complexity="1" name="CodeCoverageRepro.Controllers.WeatherForecastController.&lt;&gt;c" filename="C:\Github\PartialClassCodeCoverage\src\CodeCoverageRepro\Controllers\WeatherForecastController.cs">
          <methods>
            <method line-rate="0" branch-rate="1" complexity="1" name="&lt;Get&gt;b__3_0" signature="(int)">
              <lines>
                <line number="24" hits="0" branch="False" />
                <line number="25" hits="0" branch="False" />
                <line number="26" hits="0" branch="False" />
                <line number="27" hits="0" branch="False" />
                <line number="28" hits="0" branch="False" />
                <line number="29" hits="0" branch="False" />
              </lines>
            </method>
          </methods>
          <lines>
            <line number="24" hits="0" branch="False" />
            <line number="25" hits="0" branch="False" />
            <line number="26" hits="0" branch="False" />
            <line number="27" hits="0" branch="False" />
            <line number="28" hits="0" branch="False" />
            <line number="29" hits="0" branch="False" />
          </lines>
        </class>
      </classes>
    </package>
  </packages>
</coverage>
```
</details>

**Comment by jakubch1** [comment]
Issue is fixed in package: https://dev.azure.com/dnceng/public/_artifacts/feed/test-tools/NuGet/Microsoft.CodeCoverage/overview/17.7.0-preview.23204.2

**Comment by adc-cjewett** [comment]
@jakubch1 Sorry still not clear to me how to test these changes. Given the reproduce example above (https://github.com/adc-cjewett/PartialClassCodeCoverage) I'm not sure referencing the package directly is applicable. If we have a runsettings file or use the command line `dotnet test --collect:"Code Coverage;Format=Cobertura"` how would one use the perview version in those scenarios?

**Comment by jakubch1** [comment]
@adc-cjewett you have 2 options:

First option is to reference preview Microsoft.CodeCoverage package in your test project. Do below changes:
```
D:\github\PartialClassCodeCoverage [previewcoverage]> git diff main
diff --git a/nuget.config b/nuget.config
new file mode 100644
index 0000000..d2c8f85
--- /dev/null
+++ b/nuget.config
@@ -0,0 +1,8 @@
+<?xml version="1.0" encoding="utf-8"?>
+<configuration>
+  <packageSources>
+    <clear />
+    <add key="NuGet official package source" value="https://api.nuget.org/v3/index.json" />
+    <add key="test-tools" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/test-tools/nuget/v3/index.json" />
+  </packageSources>
+</configuration>
\ No newline at end of file
diff --git a/test/WebApplication.Tests/WebApplication.Tests.csproj b/test/WebApplication.Tests/WebApplication.Tests.csproj
index 38507ad..8caab6f 100644
--- a/test/WebApplication.Tests/WebApplication.Tests.csproj
+++ b/test/WebApplication.Tests/WebApplication.Tests.csproj
@@ -13,6 +13,7 @@
     <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
     <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
     <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
+    <PackageReference Include="Microsoft.CodeCoverage" Version="17.7.0-preview.23204.2" />^M
   </ItemGroup>

   <ItemGroup>
```
then you can run `dotnet test --collect:"Code Coverage;Format=Cobertura"`


Second option is use tool dotnet-coverage tool:
```
dotnet tool install -g dotnet-coverage
dotnet-coverage collect -f Cobertura "dotnet test"
```
Latest version 17.7.0 contains fixes that you need.

**Comment by adc-cjewett** [comment]
@jakubch1  Thanks for the clarification! I did a test and also included a ReportGenerator report which the extension FineCodeCoverage relies on to display code coverage inline.

Looking at the raw Cobertura file that was output it looks good. Maybe one thing that is odd is that the Bitbucket.cs contains the constructor code coverage information for the other files which I would not have expected. Is that a bug?

I also ran the report through ReportGenerator and it seems like the code coverage is being misrepresented in the HTML report output by that tool. The report looks like this: ![image](https://user-images.githubusercontent.com/118358736/230030730-eb09c772-25cc-4e5c-8750-1eb2db0a0d07.png)

I imagine it is due to the `name` attribute in the `class` element being the same across all partial class files, but I want to run Coverlet later in the day to compare its output.

**Comment by jakubch1** [comment]
In reality all constructors from other files at the beginning are initializing `Files` property in Bitbucket.cs. The only way to keep this information was to add those constructors also into Bitbucket.cs. So basically if method contains more than 1 source file we are duplicating it in all source files but with only those lines that they are touching in particular file.

I've used latest report generator and got good results:
![image](https://user-images.githubusercontent.com/59966772/230044914-2c0f23e2-4882-4168-a5ae-93ab65738f38.png)
![image](https://user-images.githubusercontent.com/59966772/230045098-6b6ad09a-e820-4045-99f6-e71524581a9e.png)

**Comment by adc-cjewett** [comment]
@jakubch1  Understood on the behavior of the Cobertura results. Sounds fine to me!

In regards to ReportGenerator output I'm not seeing the same result with the latest version of the tool. 
![image](https://user-images.githubusercontent.com/118358736/230151942-fcc14f05-c5d5-489d-9712-573476f37545.png)

I run the following command `reportgenerator -reports:preview_version.cobertura.xml -targetdir:coveragereport`  and it outputs different Html than what you've shown in your screenshot. Does that command look similar to yours?
