### ISSUE TITLE
CG alert: dotnet-coverage 17.6.9 "Missing legal information"

### ISSUE THREAD

**Issue by RussKie** [microsoft/codecoverage#27]
Affected component: dotnet-coverage 17.6.9
More infor: https://dev.azure.com/dnceng/internal/_componentGovernance/211420/alert/7811258?typeId=15057836&pipelinesTrackingFilter=0

**Comment by jakubch1** [comment]
Should be fixed now: https://github.com/clearlydefined/curated-data/pull/24062/files

**Comment by RussKie** [comment]
I'm still seeing the CG alerts. E.g., [for v17.7.1](https://dev.azure.com/dnceng/internal/_componentGovernance/Azure-dotnet-extensions-experimental/alert/7928075?typeId=15848802&pipelinesTrackingFilter=0).

Does https://github.com/clearlydefined/curated-data/blob/master/curations/nuget/nuget/-/dotnet-coverage.yaml need to be updated for _every_ published version? 
https://github.com/clearlydefined/curated-data/issues/22308
